# Generated by Django 3.0.1 on 2021-01-31 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curator',
            name='birth_date',
        ),
    ]
