# Generated by Django 3.0.1 on 2021-01-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_remove_curator_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curator',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
