# Generated by Django 3.0.1 on 2021-01-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20210131_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='curator',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
