# Generated by Django 3.0.1 on 2021-01-31 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_curator_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curator',
            name='active',
        ),
    ]
