# Generated by Django 3.0.1 on 2020-03-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curation',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
    ]
