# Generated by Django 3.0.1 on 2020-04-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curation', '0002_curation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='curation',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='validated'),
        ),
    ]
