# Generated by Django 3.0.1 on 2020-03-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(default='Regular', verbose_name='status')),
                ('database', models.CharField(blank=True, choices=[('GEO', 'Gene Expression Omnibus @ NCBI-NIH'), ('AE', 'ArrayExpress @ EMBL-EBI')], max_length=200, verbose_name='database')),
                ('title', models.TextField(blank=True, verbose_name='title')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('design', models.TextField(blank=True, verbose_name='design')),
                ('platform', models.TextField(blank=True, verbose_name='platform')),
                ('technology', models.TextField(blank=True, verbose_name='technology')),
                ('count', models.IntegerField(default=0, verbose_name='count')),
                ('processed_data', models.TextField(blank=True, verbose_name='processed_data')),
            ],
        ),
    ]
