# Generated by Django 3.0.1 on 2021-01-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
    ]
